name: health_app
description: A new Flutter application.


version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  font_awesome_flutter: ^8.4.0
  charts_flutter: ^0.9.0
  firebase_core: ^0.4.4+2
  firebase_auth: ^0.15.5+2
  cloud_firestore: ^0.13.4+1
  modal_progress_hud: ^0.1.3
  google_maps_flutter: ^0.5.24+1
  image_picker: ^0.6.3+4
  flutter_cupertino_date_picker: ^0.8.0
  intl: ^0.15.8
  geolocator: ^5.3.0
  animated_text_kit: ^2.0.0
  flutter_sparkline: ^0.1.0
  location: ^2.5.4
  shared_preferences: 0.5.6+3
  flutter_counter: ^1.0.3
  syncfusion_flutter_charts: ^18.1.44
  dio: 3.0.9
  table_calendar: ^2.2.3


dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  assets:
    - images/


